 [versions]
 kotlin = "2.2.20-RC2"
 paper = "1.21.10-R0.1-SNAPSHOT"
 papi = "2.11.7"
 luckperms = "5.4"

 [libraries]
 paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
 papi = { group = "me.clip", name = "placeholderapi", version.ref = "papi"}
 luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms"}