 [versions]
 kotlin = "2.2.20-RC2"
 blossom = "2.1.0"
 paper = "1.21.11-R0.1-SNAPSHOT"
 bungee = "1.21-R0.4"
 velocity = "3.5.0-SNAPSHOT"
 papi = "2.11.7"
 luckperms = "5.4"

 [libraries]
 paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
 bungee = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungee" }
 velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
 papi = { group = "me.clip", name = "placeholderapi", version.ref = "papi"}
 luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms"}

 [plugins]
 blossom = { id = "net.kyori.blossom", version.ref = "blossom" }